### ISSUE TITLE
OneDriveSDK Saver doesn't work in Android 11

### ISSUE THREAD

**Issue by bishinew** [OneDrive/onedrive-api-docs#1410]
After updated device to Android 11, OneDriveSDK Saver doesn't work anymore. Picker is still working.

Please help!

Let us know if you need more info.

Thanks

2020-10-17 17:55:39.058 29781-29781/com.example.onedrivesdk.saversample W/System.err: com.microsoft.onedrivesdk.saver.SaverException
2020-10-17 17:55:39.058 29781-29781/com.example.onedrivesdk.saversample W/System.err: at com.microsoft.onedrivesdk.saver.Saver.handleSave(Saver.java:110)
2020-10-17 17:55:39.058 29781-29781/com.example.onedrivesdk.saversample W/System.err: at com.example.onedrivesdk.saversample.SaverMain.onActivityResult(SaverMain.java:121)
2020-10-17 17:55:39.058 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.Activity.dispatchActivityResult(Activity.java:8310)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.os.Handler.dispatchMessage(Handler.java:106)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.os.Looper.loop(Looper.java:223)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7656)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at java.lang.reflect.Method.invoke(Native Method)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-10-17 17:55:39.059 29781-29781/com.example.onedrivesdk.saversample W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

![image](https://user-images.githubusercontent.com/3579886/101508232-05524c80-393d-11eb-8b52-0ddb4eaa1771.png)

**Comment by bishinew** [comment]
We have been using this API for a while. This API forces users to download OneDrive app. It promotes Microsoft's app. As a third party developer, we can simplify the development.

Thanks

**Comment by patrick-rodgers** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
