### ISSUE TITLE
[Quesion] receiving 500 while file download is in progress and moved the file succesfully

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#154]
did the following steps

step1) file downloading started (file size around 45 MB)
step2) during download, moved file to other folder using move api
step3) move operation was successful, and file was getting download
step4) *** after some time received 500 error in file download, with 2 different exception are as follows

1st) 500 error (while downloading)
javax.net.ssl.SSLException: Read error: ssl=0x71d99948: I/O error during system call, Connection reset by peer

Caused by: Read error: ssl=0x71d99948: I/O error during system call, Connection reset by peer
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:677)
at ch.boye.httpclientandroidlib.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:204)
at ch.boye.httpclientandroidlib.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:177)
at ch.boye.httpclientandroidlib.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:201)
at ch.boye.httpclientandroidlib.conn.EofSensorInputStream.read(EofSensorInputStream.java:155

2nd) 500 error (while downloading) 
java.net.SocketTimeoutException: Read timed out

Caused by: Read timed out
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:677)
at ch.boye.httpclientandroidlib.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:204)
at ch.boye.httpclientandroidlib.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:177)
at ch.boye.httpclientandroidlib.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:201)
at ch.boye.httpclientandroidlib.conn.EofSensorInputStream.read(EofSensorInputStream.java:155)

what it is happening so?

**Comment by rgregg** [comment]
Are you seeing this behavior with OneDrive personal or business?

**Comment by ankit-ankuagrawal** [comment]
@ryan gregg for onedrive business

**Comment by rgregg** [comment]
https://login.microsoftonline.com/common/oauth2/logout

**Comment by rgregg** [comment]
Closing out old issues. If this continues to be an issue, please reopen and provide additional details.
