### ISSUE TITLE
Error thrown in Js Sdk: e.data.indexOf is not a function  #1290

### ISSUE THREAD

**Issue by salahbm** [OneDrive/onedrive-api-docs#1763]
#### Category
- [x] Question
- [x] Bug

#### Sign In and Save to OneDrive
```
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js" async defer></script>
    <title>Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <input id="fileUploadControl" name="fileUploadControl" type="file" />
    <button onclick="launchSaveToOneDrive()">Save to OneDrive</button>
  
    <script type="text/javascript">
      function launchSaveToOneDrive() {
        console.log('Launching save to OneDrive...');
        try {
          let odOptions = {
            clientId: "b1a649b1-9c86-4a97-8780-a92ea687bf32",
            action: "save",
            sourceInputElementId: "fileUploadControl",
            fileName: "test.txt",
            openInNewWindow: false,
            advanced: {
              redirectUri: "http://localhost:5173"
            },
            success: function(files) {
              console.log('Save successful:', files);
            },
            progress: function(percent) {
              console.log('Save progress:', percent);
            },
            cancel: function() {
              console.log('Save canceled');
            },
            error: function(error) {
              console.error('Save error:', error);
            }
          };
  
          OneDrive.save(odOptions);
        } catch (error) {
          console.error('Error launching save operation:', error.message);
        }
      }
    </script>
  </body>
```
####ERROR

```
1. OneDrive.js:4 Uncaught TypeError: e.data.indexOf is not a function
    at OneDrive.js:4:19110
    
 2.  Failed due to Unknown Error: Error at new e (https://js.live.net/v7.2/OneDrive.js:4:32744) at https://js.live.net/v7.2/OneDrive.js:4:19308
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by jainam-shah-cygnet** [comment]
I am facing the same error while I want to open oneDrive for pick a file. (**OneDrive.open(odOptions);**)

**Comment by nayanprasad** [comment]
did you find any solution for this? i'm also getting the same error

**Comment by rabbygit** [comment]
I am encountering the same problem while attempting to call `OneDrive.open(options)` function.

**Comment by AvulaPooja** [comment]
Any solution for this issue ?

**Comment by rabbygit** [comment]
I think I've found the root cause of this issue. The `u.onMessage` event listener https://prnt.sc/xUZxD26SJlzI can be fired from another window pop-up. The `e.data` is supposed to be a JSON string https://prnt.sc/Z0MndPAi7x3I but in my case, the `u.onMessage` event listener is fired from the **react-dev-tools** and the `e.data` becomes an object https://prnt.sc/rfQsntoYzT30. it causes the error. We can fix the issue by adding an extra string type check https://prnt.sc/R6EDK-bZXz2x.

**Comment by talha-naseeb** [comment]
Did you clear this bug ?
Uncaught TypeError: e.data.indexOf is not a function
    at OneDrive.js:4:19110
    this error encounter when i integrate onedrive in my react project , but it perfectly works in the template Code provided by Azrue...

**Comment by AvulaPooja** [comment]
Now , It is working fine, I'm not getting this - **Uncaught TypeError: e.data.indexOf is not a function** error anymore.

**Comment by talha-naseeb** [comment]
> Now , It is working fine, I'm not getting this - **Uncaught TypeError: e.data.indexOf is not a function** error anymore.

what did you , install new version of it or anyother approch ?

**Comment by AvulaPooja** [comment]
v7.2 , I have used, it's working perfectly

**Comment by talha-naseeb** [comment]
Did you integrate one drive in React ?

**Comment by AvulaPooja** [comment]
In Angular

**Comment by talha-naseeb** [comment]
I install 2 dependencies ,
msla-browser 3.24 and msal-react 2.1
Which version are you taking about?

**Comment by AvulaPooja** [comment]
"@azure/msal-angular": "^3.0.23",
    "@azure/msal-browser": "^3.22.0",

**Comment by talha-naseeb** [comment]
Did you wrap you component in AuthenticatedTemplate ? 
Or can you give me your script for testing ? really appericicate for that

**Comment by AvulaPooja** [comment]
Actually,I'm bit busy with different things , can u ping me tmrw for that

**Comment by talha-naseeb** [comment]
Okay Sure !

**Comment by AvulaPooja** [comment]
did u find the solution, to your issue

**Comment by talha-naseeb** [comment]
Yes , I mail the issue to Microsoft support.  They said they will open the
community to check the issue .
And I found I one thing the script successfully run in edge but get issue
in chrome

**Comment by Raghav-Sao** [comment]
I got the issue, in my case it was conditionally showing one drive code...which was causing the issue...
So I simply added another OneDrive button, which launches onedrive with a hidden class, and now the conditional open drive button is also working...

i think it's mandatory to load the script while the page is loading, conditional rendering won't work....

I'm using Next.js and the same issue I was getting when I shifted the OneDrive button to dialogue, which was conditionally open on some user action...
@AvulaPooja  @talha-naseeb

**Comment by talha-naseeb** [comment]
Hi ,
You need to relaod you script first then open the drive , it will works
perfectly, so you can do one thing add the setitmeout on it and call the
script at that time and after reload you can call the drive

**Comment by Raghav-Sao** [comment]
ok sure will try tysm @talha-naseeb

**Comment by talha-naseeb** [comment]
Is your issue solved ?

**Comment by raghav-thirdaiautomation** [comment]
@talha-naseeb, sorry I did some alternative solution. I will check your solution and update soon. tysm
