### ISSUE TITLE
create new file return 411 client error randomly

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#549]
Hi,

I got 411  error when I tried to upload a 0 byte file without content-length from one of my msn.com account but server doesn't  complaint about content-length on the other account. (same request, same file). 

Why do you have different behaviour of a api on different account? and the response not a json.

```
411 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">^M
<HTML><HEAD><TITLE>Length Required</TITLE>^M
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>^M
<BODY><h2>Length Required</h2>^M
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>^M
</BODY></HTML>^M
 caused by Traceback (most recent call last):
  File "./package/src/shared/python-lib/ucc/common.py", line 29, in outter_func
  File "./package/src/shared/python-lib/ucc/onedrive.py", line 691, in create_file
  File "./package/src/shared/python-lib/ucc/onedrive.py", line 354, in _upload_file
  File "./package/src/shared/python-lib/ucc/onedrive.py", line 281, in _simple_upload
  File "./package/src/shared/python-lib/requests/models.py", line 844, in raise_for_status
HTTPError: 411 Client Error: Length Required for url: https://api.onedrive.com/v1.0/drive/items/56F677871E996F9!70147/children/888.MYO/content?%40name.conflictBehavior=fail
```

**Comment by ificator** [comment]
The response isn't JSON as it's failing before the OneDrive API is executed - it's the HTTP host rejecting the request. Given that, it's hard to see how two different accounts would behave differently. Is it possible for you to get request/responses captures (using something like fiddler, postman, charles, etc) for both the user that failed and the user that succeeded?

**Comment by verybada** [comment]
# Workable account
request
```
method PUT url https://api.onedrive.com/v1.0/drive/items/5F663FB20714AA03!101/children/empty.txt/content?%40name.conflictBehavior=fail headers {'Transfer-Encoding': 'chunked', 'Authorization': 'xxx'}
```
response
```
resp status code 201 content {"@odata.context":"https://api.onedrive.com/v1.0/$metadata#drives('me')/items('5F663FB20714AA03%21101')/children/$entity","@content.downloadUrl":"https://gvkqww-sn3302.files.1drv.com/y3puCfYPfsBL-diMQBhgBJ68uWNYZuAaB1nV55jJc_h7p08F_DW4GOMS3bY8EFFXWLUHJJkE6BjVWRRIfFTnBbPykWwO16SEpSpf5rIBrx2JhT0jWI0nqN0Kl5u7OfjdvZ4UOV7Ts_DEjRXr9dVBwCiIRBqwyzWX65J8svzyVNJ05lg3IsvolZ-oYkx-AVz-HSzHTVgx6hex7zbyNfsJr4hqQ","createdBy":{"application":{"displayName":"xxx","id":"481543b1"},"user":{"displayName":"adam lin","id":"5f663fb20714aa03"}},"createdDateTime":"2017-03-16T06:14:24.443Z","cTag":"aYzo1RjY2M0ZCMjA3MTRBQTAzITExMDMzLjI1Nw","eTag":"aNUY2NjNGQjIwNzE0QUEwMyExMTAzMy4w","id":"5F663FB20714AA03!11033","lastModifiedBy":{"application":{"displayName":"xxxx","id":"481543b1"},"user":{"displayName":"adam lin","id":"5f663fb20714aa03"}},"lastModifiedDateTime":"2017-03-16T06:14:24.443Z","name":"empty.txt","parentReference":{"driveId":"5f663fb20714aa03","id":"5F663FB20714AA03!101","path":"/drive/root:"},"size":0,"webUrl":"https://1drv.ms/t/s!AAOqFAeyP2Zf1hk","file":{"hashes":{"crc32Hash":"00000000","sha1Hash":"DA39A3EE5E6B4B0D3255BFEF95601890AFD80709"},"mimeType":"text/plain"},"fileSystemInfo":{"createdDateTime":"2017-03-16T06:14:24.443Z","lastModifiedDateTime":"2017-03-16T06:14:24.443Z"}}
```

# Bad one
request
```
method PUT url https://api.onedrive.com/v1.0/drive/items/56F677871E996F9!267/children/empty.txt/content?%40name.conflictBehavior=fail headers {'Transfer-Encoding': 'chunked', 'Authorization': 'xxx'}
```
response
```
resp status code 411 content <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>

411 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

**Comment by ificator** [comment]
Thanks @verybada, those were very useful. I think I see what the issue is and we'll working on getting it fixed.

**Comment by ificator** [comment]
This issue should now hopefully be resolved!
