### ISSUE TITLE
401 Unauthorized while using "files.readwrite" scope 

### ISSUE THREAD

**Issue by guruprasad211** [OneDrive/onedrive-api-docs#705]
{ StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/home/nowconfer/NowConfer-1.0.1.0/node_modules/onedrive-api/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/nowconfer/NowConfer-1.0.1.0/node_modules/onedrive-api/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/home/nowconfer/NowConfer-1.0.1.0/node_modules/onedrive-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/nowconfer/NowConfer-1.0.1.0/node_modules/onedrive-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/nowconfer/NowConfer-1.0.1.0/node_modules/onedrive-api/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'StatusCodeError',
  statusCode: 401,
  message: '401 - [object Object]',
  error:
   { error:
      { code: 'unauthenticated',
        message: 'Must be authenticated to use \'/drive\' syntax' } },
  options:
   { method: 'POST',
     uri: 'https://api.onedrive.com/v1.0/drive/items/root/children',
     headers:
      { 'Content-Type': 'application/json',
        Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFBQmxEcnFmRUZsU2F1aTZ4blJqWDVFWlhBcDJaa0x0QXhYeFhwMWF4Qm0wVGVfQnVTU1NaVEpKVUdqTlphdlpKYmE0T1k3TmV1aG1HWFJFdERjb2dVR19BdGdPNkY4ckJudVNqSk5UUEplN3lBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoiSEhCeUtVLTBEcUFxTVpoNlpGUGQyVldhT3RnIiwia2lkIjoiSEhCeUtVLTBEcUFxTVpoNlpGUGQyVldhT3RnIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mMDU3Y2IzZC1kMjBlLTQyYTgtYTJmNS05YmJmMzg4NzhkMmIvIiwiaWF0IjoxNTA1ODI3MTA4LCJuYmYiOjE1MDU4MjcxMDgsImV4cCI6MTUwNTgzMTAwOCwiYWNyIjoiMSIsImFpbyI6IlkyVmdZSkM2YXU1WUxHRXZ1eTMxMWpyN3pTRnFPbUdUYXYzWVZIeGtMYmdlbVVXSnlRQUEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik5vd2NvbmZlciIsImFwcGlkIjoiMWM5YTRkZGQtMjJjZS00MTg4LWI5YjEtYWQwZmQxYTc5MDY2IiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJQcmFzYWQiLCJnaXZlbl9uYW1lIjoiR3VydSIsImlwYWRkciI6IjIyMC4yMjcuMzguOTgiLCJuYW1lIjoiR3VydSBQcmFzYWQiLCJvaWQiOiIzNWZlOWQ0Mi1iMzJjLTRkYmYtYTBlOS1mZTIzNTUzMjc0YmYiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwM0JGRkQ4RDUzQzFDRSIsInNjcCI6IkZpbGVzLlJlYWRXcml0ZSIsInN1YiI6IkZuUFV4c1V1Y2cwV2htZzBud0NjQkY0aENFY2g2Z0VUQTVHYzQ5T3NQd1EiLCJ0aWQiOiJmMDU3Y2IzZC1kMjBlLTQyYTgtYTJmNS05YmJmMzg4NzhkMmIiLCJ1bmlxdWVfbmFtZSI6Imd1cnVwcmFzYWRAdGVsZWRuYS5jb20iLCJ1cG4iOiJndXJ1cHJhc2FkQHRlbGVkbmEuY29tIiwidXRpIjoiY2x6SUJUeTA4MFNvYUdUVXNkaGlBQSIsInZlciI6IjEuMCJ9.' },
     body: { name: 'Test1', folder: {} },
     json: true,

onedrive.readwrite scope is saying invalid scope, please any one help me in solving this error, unable to create folder and upload files to onedrive.

i have used passport-azure-ad node module for outh2 and also use simple-oauth2 node module on both the scenarios i am getting the same error

**Comment by ificator** [comment]
The token you're providing appears to be for `https://graph.microsoft.com`, but it's being used directly against `https://api.onedrive.com`. Try switching to the graph endpoint and seeing if that works:

```
POST https://graph.microsoft.com/v1.0/me/drive/root/children
```

**Comment by guruprasad211** [comment]
thank you ificator, its working fine after replacing https://api.onedrive.com. to https://graph.microsoft.com,
